version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    ports:
      - "8000:8000"
    networks:
      - cvnet
    env_file:
      - .env


  react_frontend:
    build:
      context: .
      dockerfile: Dockerfile.react
    ports:
      - "3000:3000"
    networks:
      - cvnet
    environment:
      - VITE_API_URL=http://localhost:8000
  
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: cv_parser
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - cvnet

volumes:
  postgres_data:

networks:
  cvnet:
